server:
  port: 9249

spring:
  profiles: dev
  application:
    name: qas
  datasource:
    url: jdbc:mariadb://localhost:3306/qas
    username: ny
    password: rot1234!
    sql-script-encoding: UTF-8
    hikari:
      idle-timeout: 300
      max-lifetime: 300