server:
  port: 8080

spring:
  application:
    name: handycnt
  datasource:
    url: jdbc:mariadb://testdb.clp2ztogrluw.ap-northeast-2.rds.amazonaws.com:3306/hs_test
    username: admin
    password: Illunex123!
    driver-class-name: org.mariadb.jdbc.Driver
    sql-script-encoding: UTF-8